### ISSUE TITLE
Game Crashes when breaking block with falling node.

### ISSUE THREAD

**Issue by Jo5629** [minetestia/simple-woodcutter#5]
The game crashed whenever I break a block near falling gravel/sand. I fixed this problem by adding one line of code in the digger function.

`if digger == nil then return end`

I hope this will make your mod better :)

**Comment by lua-rocks** [comment]
I can't reproduce this bug, don't understand how player can be nil and how it has to do with the falling block, but I'll add your fix, thanks!
